site_name: shrtnr-docs
theme:
  name: material
docs_dir: "./docs_src"
site_dir: "./docs"
repo_url: "https://github.com/terrance00/shrtnr-docs"
repo_name: "shrtnr-docs"
site_description: "shrtnr.io - Architecture and design"
site_author: "Terrance Jevon"
edit_uri: "blob/master/docs_src/"

nav:
  - Introduction: "./index.md"
  - "Architectural Overview": "./architectural-overview.md"
  - "Data Stores":
      - "Shrtnr Redirector Store": "./data-stores/shrtnr-redirector-store.md"
      - "Shrtnr Db": "./data-stores/shrtnr-db.md"
  - "Services":
      - "API": "./services/shrtnr-api.md"
      - "OIDC": "./services/shrtnr-oidc.md"
      - "Redirector": "./services/shrtnr-redirector.md"
      - "Shrtnr UI": "./services/shrtnr-ui.md"
      - "Shrtnr Analytics": "./services/shrtnr-analytics.md"
  - "SDLC":
      - "Pull Requests": "./sdlc/pull-requests.md"
      - "QA": "./sdlc/qa.md"
      - "Bugs": "./sdlc/bugs.md"
      - "Release Cycle": "./sdlc/release-cycle.md"
  - "CI/CD":
      - "Branching Strategy": "./ci-cd/branching-strategy.md"
      - "Automation": "./ci-cd/automation.md"

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
